#!/usr/bin/env python3
"""vaseweld 1.3.0 - weld two G-code files so spiral vase mode can start or stop partway up.

Standalone build: no install, no dependencies, Python 3.10+.
Generated by tools/build_single_file.py; edit src/vaseweld/ instead.

    python vaseweld.py weld --normal base.gcode --vase body.gcode --at 12.4 -o out.gcode
    python vaseweld.py check out.gcode

MIT licensed. https://github.com/Booyaka101/vaseweld
"""

from __future__ import annotations

import argparse
import bisect
import json
import math
import os
import re
import statistics
import struct
import sys
import zlib
from dataclasses import dataclass, field, replace
from pathlib import Path


# ---------------------------------------------------------------
# __init__.py
# ---------------------------------------------------------------

__version__ = "1.3.0"

__all__ = ["__version__"]


# ---------------------------------------------------------------
# bgcode.py
# ---------------------------------------------------------------

MAGIC = b"GCDE"

_FILE_METADATA = 0
_GCODE = 1
_SLICER_METADATA = 2
_PRINT_METADATA = 4
_THUMBNAIL = 5

_DEFLATE = 1
_HEATSHRINK_11_4 = 2
_HEATSHRINK_12_4 = 3

_MEATPACK = 1
_MEATPACK_COMMENTS = 2

# The 16 characters MeatPack can pack two-to-a-byte. 0xF means "not packed, the real
# byte follows"; 0xB is a space unless the no-spaces command swapped it for 'E'.
_PACKED = "0123456789. \nGX"
_SIGNAL = 0xFF
_ENABLE_PACKING = 251
_DISABLE_PACKING = 250
_RESET_ALL = 249
_ENABLE_NO_SPACES = 247
_DISABLE_NO_SPACES = 246

# G-line parameters, which the binariser is free to drop the space in front of.
_PARAMETERS = frozenset("XYZEFIJRSGPWHCA")

_CONFIG_MARKERS = {
    "OrcaSlicer": ("; CONFIG_BLOCK_START", "; CONFIG_BLOCK_END"),
    "BambuStudio": ("; CONFIG_BLOCK_START", "; CONFIG_BLOCK_END"),
    "SuperSlicer": ("; SuperSlicer_config = begin", "; SuperSlicer_config = end"),
}
_DEFAULT_MARKERS = ("; prusaslicer_config = begin", "; prusaslicer_config = end")


class BgcodeError(ValueError):
    """The file claims to be binary G-code but cannot be read as one."""


def is_bgcode(raw: bytes) -> bool:
    return raw[:4] == MAGIC


def heatshrink(data: bytes, window_bits: int, lookahead_bits: int, size: int) -> bytes:
    """Decompress a heatshrink stream, stopping at ``size`` bytes.

    Tokens are read most significant bit first: a 1 bit introduces an 8-bit literal, a 0
    bit a backreference of ``window_bits`` index and ``lookahead_bits`` count, both stored
    one less than their real value. The final byte is zero-padded, so the caller's
    uncompressed size is what ends the stream rather than running out of bits.
    """
    out = bytearray()
    append = out.append
    acc = held = pos = 0
    end_of_data = len(data)
    # The widest token is the tag plus a whole backreference; refilling to that once
    # per token keeps the bit twiddling out of a helper, which this loop runs millions
    # of times on a real file.
    wanted = 1 + max(8, window_bits + lookahead_bits)
    index_mask = (1 << window_bits) - 1
    count_mask = (1 << lookahead_bits) - 1

    while len(out) < size:
        while held < wanted and pos < end_of_data:
            acc = (acc << 8) | data[pos]
            pos += 1
            held += 8
        if held < 1:
            break

        held -= 1
        literal = (acc >> held) & 1
        acc &= (1 << held) - 1

        if literal:
            if held < 8:
                break
            held -= 8
            append((acc >> held) & 0xFF)
            acc &= (1 << held) - 1
            continue

        if held < window_bits + lookahead_bits:
            break
        held -= window_bits
        index = (acc >> held) & index_mask
        held -= lookahead_bits
        count = ((acc >> held) & count_mask) + 1
        acc &= (1 << held) - 1

        start = len(out) - index - 1
        if start < 0:
            raise BgcodeError("backreference points before the start of the stream")
        stop = start + count
        if stop <= len(out):
            out += out[start:stop]
        else:
            # The match runs into what it is producing, which is how a run of one
            # repeated byte is stored. It has to be copied a byte at a time.
            for i in range(start, stop):
                append(out[i])

    if len(out) < size:
        raise BgcodeError(f"stream ended early, got {len(out)} of {size} bytes")
    return bytes(out[:size])


def meatpack(data: bytes, respace: bool) -> str:
    """Unpack a MeatPack stream, optionally putting the G-line spaces back."""
    chars: list[str] = []
    packing = no_spaces = command = False
    signals = pending = 0
    held: str | None = None

    def unpack(nibble: int) -> str:
        return "E" if nibble == 0xB and no_spaces else _PACKED[nibble]

    def receive(byte: int) -> None:
        nonlocal pending, held
        if not packing:
            chars.append(chr(byte))
            return
        if pending:
            # A full-width character owed from the previous byte. If its partner was
            # packed it was decoded already and has been waiting for this one.
            chars.append(chr(byte))
            if held is not None:
                chars.append(held)
                held = None
            pending -= 1
            return
        low, high = byte & 0xF, byte >> 4
        if low == 0xF:
            pending += 1
            if high == 0xF:
                pending += 1
            else:
                held = unpack(high)
            return
        first = unpack(low)
        chars.append(first)
        if first == "\n":
            return
        if high == 0xF:
            pending += 1
        else:
            chars.append(unpack(high))

    for byte in data:
        if byte == _SIGNAL:
            if signals:
                command, signals = True, 0
            else:
                signals = 1
            continue
        if command:
            if byte == _ENABLE_PACKING:
                packing = True
            elif byte in (_DISABLE_PACKING, _RESET_ALL):
                packing = False
            elif byte == _ENABLE_NO_SPACES:
                no_spaces = True
            elif byte == _DISABLE_NO_SPACES:
                no_spaces = False
            command = False
            continue
        if signals:
            receive(_SIGNAL)
            signals = 0
        receive(byte)

    return _respace(chars) if respace else "".join(chars)


def _respace(chars: list[str]) -> str:
    """Re-insert the spaces between G-line parameters that the binariser dropped."""
    out: list[str] = []
    spacing = False
    for char in chars:
        starts_line = not out or out[-1] == "\n"
        opened = False
        if char == "G" and starts_line:
            spacing = opened = True
        elif char == "\n":
            spacing = False
        if not opened and spacing and char in _PARAMETERS and (not out or out[-1] != " "):
            out.append(" ")
        if char != "\n" or not out or out[-1] != "\n":
            out.append(char)
    return "".join(out)


def _blocks(raw: bytes):
    """Yield ``(type, parameter, payload)`` for every block, decompressed."""
    if len(raw) < 10:
        raise BgcodeError("file is too short to hold a header")
    magic, version, checksum = struct.unpack_from("<4sIH", raw, 0)
    if magic != MAGIC:
        raise BgcodeError("missing the GCDE magic number")
    if version != 1:
        raise BgcodeError(f"version {version} is not supported, only version 1 is")
    if checksum > 1:
        raise BgcodeError(f"unknown checksum type {checksum}")

    at = 10
    while at < len(raw):
        try:
            btype, compression = struct.unpack_from("<HH", raw, at)
            at += 4
            (size,) = struct.unpack_from("<I", raw, at)
            at += 4
            stored = size
            if compression:
                (stored,) = struct.unpack_from("<I", raw, at)
                at += 4
            if btype == _THUMBNAIL:
                parameter = 0
                at += 6
            else:
                (parameter,) = struct.unpack_from("<H", raw, at)
                at += 2
        except struct.error as exc:
            raise BgcodeError("truncated block header") from exc

        payload = raw[at : at + stored]
        if len(payload) < stored:
            raise BgcodeError("truncated block data")
        at += stored + (4 if checksum else 0)

        if btype == _THUMBNAIL:
            continue
        if compression == _DEFLATE:
            try:
                payload = zlib.decompress(payload)
            except zlib.error as exc:
                raise BgcodeError(f"deflate block would not decompress ({exc})") from exc
        elif compression in (_HEATSHRINK_11_4, _HEATSHRINK_12_4):
            window = 11 if compression == _HEATSHRINK_11_4 else 12
            payload = heatshrink(payload, window, 4, size)
        elif compression:
            raise BgcodeError(f"unknown compression algorithm {compression}")
        yield btype, parameter, payload


def decode(raw: bytes) -> str:
    """Turn binary G-code into the text file the same slice would have produced."""
    gcode: list[str] = []
    producer = ""
    totals: list[str] = []
    config: list[str] = []

    for btype, parameter, payload in _blocks(raw):
        if btype == _GCODE:
            if parameter in (_MEATPACK, _MEATPACK_COMMENTS):
                gcode.append(meatpack(payload, parameter == _MEATPACK_COMMENTS))
            else:
                gcode.append(payload.decode("utf-8", errors="replace"))
            continue
        text = payload.decode("utf-8", errors="replace")
        if btype == _FILE_METADATA:
            producer = _entries(text).get("Producer", "")
        elif btype == _PRINT_METADATA:
            totals = [f"; {key} = {value}" for key, value in _entries(text).items()]
        elif btype == _SLICER_METADATA:
            config = [f"; {key} = {value}" for key, value in _entries(text).items()]

    if not gcode:
        raise BgcodeError("no G-code blocks in the file")

    lines = "".join(gcode).splitlines()
    lines += totals
    if config:
        begin, end = _DEFAULT_MARKERS
        for name, markers in _CONFIG_MARKERS.items():
            if producer.startswith(name):
                begin, end = markers
        lines += ["", begin, *config, end]
    return "\n".join(lines) + "\n"


def _entries(text: str) -> dict[str, str]:
    entries: dict[str, str] = {}
    for line in text.splitlines():
        key, sep, value = line.partition("=")
        if sep:
            entries[key.strip()] = value.strip()
    return entries


# ---------------------------------------------------------------
# parser.py
# ---------------------------------------------------------------

_LAYER_CHANGE = re.compile(r"^\s*;\s*(LAYER_CHANGE|CHANGE_LAYER)\s*$", re.IGNORECASE)
_Z_MARKER = re.compile(r"^\s*;\s*(?:Z|Z_HEIGHT)\s*:\s*(-?\d*\.?\d+)\s*$", re.IGNORECASE)
_CURA_LAYER = re.compile(r"^\s*;\s*LAYER:\s*-?\d+\s*$", re.IGNORECASE)
_CONFIG_KV = re.compile(r"^\s*;\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$")
_WORD = re.compile(r"([A-Za-z])\s*(-?\d*\.?\d+(?:[eE][-+]?\d+)?)")
_PRINTING_OBJECT = re.compile(
    r";\s*(?:start|stop)?\s*printing object.*?\bid:(\d+)\s+copy\s+(\d+)", re.IGNORECASE
)
_EXCLUDE_OBJECT = re.compile(r"^\s*EXCLUDE_OBJECT_DEFINE\s+NAME=(\S+)", re.IGNORECASE)
_M486 = re.compile(r"^\s*M486\s+S\s*(-?\d+)", re.IGNORECASE)
_E_MODE = re.compile(r"^\s*M8([23])\b", re.IGNORECASE)

CONFIG_DELIMITERS = (
    ("; prusaslicer_config = begin", "; prusaslicer_config = end"),
    ("; CONFIG_BLOCK_START", "; CONFIG_BLOCK_END"),
    ("; slic3r_config = begin", "; slic3r_config = end"),
    ("; SuperSlicer_config = begin", "; SuperSlicer_config = end"),
)


class GcodeError(Exception):
    """A G-code file could not be read or made sense of."""


@dataclass(slots=True)
class Move:
    """One G0/G1/G2/G3 line, decoded far enough to reason about Z and E."""

    cmd: str
    x: float | None = None
    y: float | None = None
    z: float | None = None
    e: float | None = None
    f: float | None = None


@dataclass
class Cursor:
    """Extruder and nozzle state while walking a run of lines."""

    relative_e: bool
    e_pos: float = 0.0
    x: float | None = None
    y: float | None = None
    retracted: float = 0.0  # millimetres of filament currently pulled back

    def copy(self) -> "Cursor":
        return replace(self)


@dataclass(slots=True)
class Step:
    """One decoded line: its E delta in millimetres and its XY travel, if any."""

    index: int
    line: str
    kind: str  # "move", "mode" or "other"
    delta: float | None
    dist: float


@dataclass(slots=True)
class Layer:
    """A printed layer: ``lines[start:end]`` of the owning file."""

    index: int  # 1-based, as printed
    z: float
    start: int
    end: int


@dataclass
class GcodeFile:
    path: Path
    lines: list[str]
    newline: str
    layers: list[Layer]
    header_end: int
    footer_start: int
    config: dict[str, str]
    config_span: tuple[int, int] | None
    layer_marker: str  # "layer_change", "cura" or "z_move"
    relative_e: bool
    object_instances: int | None = field(default=None)

    @property
    def header(self) -> list[str]:
        return self.lines[: self.header_end]

    @property
    def footer(self) -> list[str]:
        return self.lines[self.footer_start :]

    def layer_lines(self, layer: Layer) -> list[str]:
        return self.lines[layer.start : layer.end]

    def cursor(self) -> Cursor:
        return Cursor(relative_e=self.relative_e)


def strip_comment(line: str) -> tuple[str, str]:
    """Split a line into its code part and its trailing comment (including ``;``)."""
    idx = line.find(";")
    if idx < 0:
        return line, ""
    return line[:idx], line[idx:]


def parse_e_mode(line: str) -> bool | None:
    """True for M83 (relative E), False for M82, None if the line is neither."""
    match = _E_MODE.match(strip_comment(line)[0])
    return match.group(1) == "3" if match else None


def parse_move(line: str) -> Move | None:
    """Decode a linear or arc move. Returns None for anything else."""
    code, _ = strip_comment(line)
    stripped = code.lstrip()
    if not stripped or stripped[0] not in "Gg":
        return None
    words = _WORD.findall(stripped)
    if not words:
        return None
    letter, number = words[0]
    if letter not in "Gg":
        return None
    try:
        cmd = f"G{int(float(number))}"
    except ValueError:
        return None
    if cmd not in ("G0", "G1", "G2", "G3"):
        return None
    move = Move(cmd)
    for letter, number in words[1:]:
        key = letter.upper()
        if key not in ("X", "Y", "Z", "E", "F"):
            continue
        try:
            value = float(number)
        except ValueError:
            continue
        setattr(move, key.lower(), value)
    return move


def parse_g92_e(line: str) -> float | None:
    """Return the E value of a ``G92`` line, or None if it does not set E."""
    code, _ = strip_comment(line)
    if not re.match(r"^\s*G92\b", code, re.IGNORECASE):
        return None
    for letter, number in _WORD.findall(code):
        if letter.upper() == "E":
            try:
                return float(number)
            except ValueError:
                return None
    return None


def format_e(value: float) -> str:
    """Format an E value the way slicers do: up to 5 decimals, no trailing zeros."""
    text = f"{value:.5f}".rstrip("0").rstrip(".")
    return text if text not in ("", "-", "-0") else "0"


def set_e(line: str, value: float) -> str:
    """Replace the E word of a move, leaving every other word and the comment alone."""
    code, comment = strip_comment(line)
    replaced = False

    def repl(match: re.Match[str]) -> str:
        nonlocal replaced
        if match.group(1).upper() != "E" or replaced:
            return match.group(0)
        replaced = True
        return f"{match.group(1)}{format_e(value)}"

    return _WORD.sub(repl, code) + comment


def walk(lines: list[str], cursor: Cursor):
    """Yield one Step per line, advancing ``cursor``.

    This is the single place that decides what a line means for the extruder, so
    the splice, the flow ramp and the checks all agree on it.
    """
    for index, line in enumerate(lines):
        mode = parse_e_mode(line)
        if mode is not None:
            cursor.relative_e = mode
            yield Step(index, line, "mode", None, 0.0)
            continue
        reset = parse_g92_e(line)
        if reset is not None:
            cursor.e_pos = reset
            yield Step(index, line, "other", None, 0.0)
            continue
        move = parse_move(line)
        if move is None:
            yield Step(index, line, "other", None, 0.0)
            continue

        dist = 0.0
        if (move.x is not None or move.y is not None) and None not in (cursor.x, cursor.y):
            dx = (move.x if move.x is not None else cursor.x) - cursor.x
            dy = (move.y if move.y is not None else cursor.y) - cursor.y
            dist = math.hypot(dx, dy)
        if move.x is not None:
            cursor.x = move.x
        if move.y is not None:
            cursor.y = move.y

        delta = None
        if move.e is not None:
            if cursor.relative_e:
                delta = move.e
                cursor.e_pos += move.e
            else:
                delta = round(move.e - cursor.e_pos, 5)
                cursor.e_pos = move.e
            # Negative E is always a retraction, even on a wiping move that also
            # travels; positive E only counts as priming when nothing else moves.
            if delta < 0 or dist == 0:
                cursor.retracted -= delta
        yield Step(index, line, "move", delta, dist)


def state_at(gcode: GcodeFile, line_index: int) -> Cursor:
    """Extruder and nozzle state the file has reached by ``line_index``.

    The layers taken from a file assume the nozzle is where that file left it, so
    the weld has to resume from this state rather than from nothing.
    """
    cursor = Cursor(relative_e=gcode.relative_e)
    for _ in walk(gcode.lines[:line_index], cursor):
        pass
    return cursor


def config_float(config: dict[str, str], key: str, fallback: float) -> float:
    """First numeric value of a config key, which slicers sometimes write as a list."""
    for piece in config.get(key, "").split(","):
        try:
            return float(piece.strip())
        except ValueError:
            continue
    return fallback


def bead_width(area: float, height: float) -> float:
    """Width of the bead an extrusion of cross-section ``area`` leaves.

    The usual model: a rectangle of length w-h capped with semicircles of radius
    h/2, so ``area = h*w - h**2 + pi*h**2/4``. Solved for w.
    """
    if height <= 0:
        return 0.0
    return (area + height * height * (1.0 - math.pi / 4.0)) / height


def read_text(path: Path) -> tuple[list[str], str]:
    """Read a G-code file, decoding binary G-code on the way in."""
    if path.is_dir():
        raise GcodeError(f"{path}: is a directory, not a G-code file")
    try:
        raw = path.read_bytes()
    except FileNotFoundError as exc:
        raise GcodeError(f"{path}: no such file") from exc
    except PermissionError as exc:
        raise GcodeError(f"{path}: permission denied") from exc
    except OSError as exc:
        raise GcodeError(f"{path}: cannot read ({exc.strerror or exc})") from exc

    if not raw.strip():
        raise GcodeError(f"{path}: file is empty")

    if is_bgcode(raw):
        try:
            return decode(raw).splitlines(), "\n"
        except BgcodeError as exc:
            raise GcodeError(f"{path}: {exc}") from exc
    if path.suffix.lower() == ".bgcode":
        raise GcodeError(
            f"{path}: named .bgcode but does not start with the GCDE magic number. "
            "Re-export it from the slicer."
        )

    text = raw.decode("utf-8", errors="replace")
    newline = "\r\n" if text.count("\r\n") > text.count("\n") // 2 else "\n"
    return text.splitlines(), newline


def parse_config(lines: list[str]) -> tuple[dict[str, str], tuple[int, int] | None]:
    """Read the trailing slicer config comment block into a plain dict."""
    for begin_marker, end_marker in CONFIG_DELIMITERS:
        begin = end = None
        for i in range(len(lines) - 1, -1, -1):
            line = lines[i].strip()
            if end is None and line == end_marker:
                end = i
            elif end is not None and line == begin_marker:
                begin = i
                break
        if begin is None or end is None:
            continue
        config: dict[str, str] = {}
        for line in lines[begin + 1 : end]:
            match = _CONFIG_KV.match(line)
            if match:
                config[match.group(1)] = match.group(2)
        return config, (begin, end)
    return {}, None


def _detect_layer_starts(lines: list[str], scan: range) -> tuple[list[int], str]:
    starts = [i for i in scan if _LAYER_CHANGE.match(lines[i])]
    if starts:
        return starts, "layer_change"
    starts = [i for i in scan if _CURA_LAYER.match(lines[i])]
    if starts:
        return starts, "cura"

    starts = []
    current_z: float | None = None
    for i in scan:
        move = parse_move(lines[i])
        if move is None or move.z is None:
            continue
        if move.x is not None or move.y is not None or move.e is not None:
            continue
        if current_z is None or move.z > current_z + 1e-9:
            starts.append(i)
            current_z = move.z
    return starts, "z_move"


def _layer_z(lines: list[str], start: int, end: int) -> float | None:
    for i in range(start, min(start + 6, end)):
        match = _Z_MARKER.match(lines[i])
        if match:
            return float(match.group(1))
    for i in range(start, end):
        move = parse_move(lines[i])
        if move is not None and move.z is not None:
            return move.z
    return None


def _find_footer_start(lines: list[str], last_layer_start: int) -> int:
    last_extruding = last_layer_start
    for i in range(last_layer_start, len(lines)):
        move = parse_move(lines[i])
        if move is not None and move.e is not None:
            last_extruding = i
    custom = None
    for i in range(last_extruding + 1, len(lines)):
        if lines[i].strip().lower() == ";type:custom":
            custom = i
            break
    return custom if custom is not None else last_extruding + 1


def _detect_relative_e(lines: list[str], header_end: int, config: dict[str, str]) -> bool:
    for line in lines[:header_end]:
        mode = parse_e_mode(line)
        if mode is not None:
            return mode
    return config.get("use_relative_e_distances", "0").strip() in ("1", "true", "True")


def find_objects_info(lines: list[str], config: dict[str, str]) -> str | None:
    """PrusaSlicer writes ``; objects_info = {...}`` just outside the config block."""
    if config.get("objects_info"):
        return config["objects_info"]
    for line in reversed(lines):
        match = _CONFIG_KV.match(line)
        if match and match.group(1) == "objects_info":
            return match.group(2)
    return None


def _count_object_instances(lines: list[str], config: dict[str, str]) -> int | None:
    info = find_objects_info(lines, config)
    if info:
        count = info.count('"name"')
        if count:
            return count
    pairs = set()
    names = set()
    ids = set()
    for line in lines:
        match = _PRINTING_OBJECT.search(line)
        if match:
            pairs.add((match.group(1), match.group(2)))
            continue
        match = _EXCLUDE_OBJECT.match(line.strip())
        if match:
            names.add(match.group(1))
            continue
        match = _M486.match(line)
        if match and int(match.group(1)) >= 0:
            ids.add(match.group(1))
    for candidate in (pairs, names, ids):
        if candidate:
            return len(candidate)
    return None


def parse_file(path: str | Path) -> GcodeFile:
    """Parse a sliced G-code file. Raises GcodeError on anything unusable."""
    path = Path(path)
    lines, newline = read_text(path)
    config, config_span = parse_config(lines)
    # PrusaSlicer and OrcaSlicer append the config block; BambuStudio puts it near
    # the top. Either way it is not part of the print, so keep it out of the scan.
    scan = range(len(lines))
    if config_span:
        begin, end = config_span
        scan = range(end + 1, len(lines)) if begin < len(lines) // 2 else range(begin)

    starts, marker = _detect_layer_starts(lines, scan)
    if not starts:
        raise GcodeError(
            f"{path}: no layers found. Expected ';LAYER_CHANGE' markers or bare Z moves. "
            "Is this a sliced G-code file?"
        )

    footer_start = _find_footer_start(lines, starts[-1])
    bounds = starts + [footer_start]
    layers: list[Layer] = []
    for i, start in enumerate(starts):
        end = bounds[i + 1]
        z = _layer_z(lines, start, end)
        if z is None:
            continue
        # Spiral vase emits its flow ramp-down as a second block at the final Z;
        # that is a continuation of the layer, not a new one.
        if layers and z <= layers[-1].z + 1e-9:
            layers[-1].end = end
            continue
        layers.append(Layer(index=len(layers) + 1, z=z, start=start, end=end))
    if len(layers) < 2:
        raise GcodeError(f"{path}: only {len(layers)} layer(s) found; nothing to weld")

    header_end = layers[0].start
    return GcodeFile(
        path=path,
        lines=lines,
        newline=newline,
        layers=layers,
        header_end=header_end,
        footer_start=footer_start,
        config=config,
        config_span=config_span,
        layer_marker=marker,
        relative_e=_detect_relative_e(lines, header_end, config),
        object_instances=_count_object_instances(lines, config),
    )


# ---------------------------------------------------------------
# compat.py
# ---------------------------------------------------------------

# Quoted verbatim from PrusaSlicer's own validator (Print::validate).
SINGLE_MATERIAL_MSG = (
    "The Spiral Vase option can only be used when printing single material objects."
)
SINGLE_OBJECT_MSG = (
    "Only a single object may be printed at a time in Spiral Vase mode. "
    'Either remove all but the last object, or enable sequential mode by "complete_objects".'
)

COMPARED_FIELDS = (
    "layer_height",
    "first_layer_height",
    "nozzle_diameter",
    "filament_diameter",
    "bed_shape",
    "printer_model",
)

_TOOL = re.compile(r"^\s*T(\d+)\s*$")
_SKIRT_TYPE = re.compile(r"^\s*;\s*TYPE:\s*(.*?)\s*$", re.IGNORECASE)
_POLYGON = re.compile(r'"polygon"\s*:\s*\[(.*?)\]\]', re.DOTALL)
_PLACEMENT_TOLERANCE_MM = 0.05


class CompatError(Exception):
    """The two files cannot be welded. The message names the offending field."""


@dataclass(frozen=True)
class Footprint:
    min_x: float
    min_y: float
    max_x: float
    max_y: float

    def differs_from(self, other: "Footprint", tolerance: float) -> bool:
        return any(
            abs(a - b) > tolerance
            for a, b in zip(
                (self.min_x, self.min_y, self.max_x, self.max_y),
                (other.min_x, other.min_y, other.max_x, other.max_y),
            )
        )

    def __str__(self) -> str:
        return f"X {self.min_x:.3f}-{self.max_x:.3f}, Y {self.min_y:.3f}-{self.max_y:.3f}"


def normalise(field: str, value: str) -> str:
    """Collapse the formatting differences between slicers (``0.200`` vs ``0.2``)."""
    value = value.strip()
    if field == "bed_shape":
        parts = []
        for point in value.split(","):
            coords = point.strip().split("x")
            try:
                parts.append("x".join(f"{float(c):g}" for c in coords))
            except ValueError:
                parts.append(point.strip())
        return ",".join(parts)
    pieces = []
    for piece in value.split(","):
        piece = piece.strip()
        try:
            pieces.append(f"{float(piece):g}")
        except ValueError:
            pieces.append(piece)
    return ",".join(pieces)


def tools_used(gcode: GcodeFile) -> set[int]:
    """Tool indices actually selected in the print body."""
    tools: set[int] = set()
    for line in gcode.lines[gcode.header_end : gcode.footer_start]:
        code, _ = strip_comment(line)
        match = _TOOL.match(code)
        if match:
            tools.add(int(match.group(1)))
    return tools or {0}


def first_layer_footprint(gcode: GcodeFile) -> Footprint | None:
    """Bounding box of the object extrusions on layer 1, skirt and brim excluded."""
    layer = gcode.layers[0]
    x = y = None
    section = ""
    xs: list[float] = []
    ys: list[float] = []
    for line in gcode.layer_lines(layer):
        marker = _SKIRT_TYPE.match(line)
        if marker:
            section = marker.group(1).lower()
        move = parse_move(line)
        if move is None:
            continue
        if move.x is not None:
            x = move.x
        if move.y is not None:
            y = move.y
        if move.e is None or move.e <= 0:
            continue
        if move.x is None and move.y is None:
            continue
        if "skirt" in section or "brim" in section:
            continue
        if x is not None and y is not None:
            xs.append(x)
            ys.append(y)
    if not xs:
        return None
    return Footprint(min(xs), min(ys), max(xs), max(ys))


def object_polygons(gcode: GcodeFile) -> list[str] | None:
    """Rounded object outlines from ``objects_info``, if the slicer wrote them."""
    info = find_objects_info(gcode.lines, gcode.config)
    if not info:
        return None
    polygons = []
    for body in _POLYGON.findall(info):
        points = re.findall(r"-?\d*\.?\d+", body)
        polygons.append(",".join(f"{float(p):.2f}" for p in points))
    return sorted(polygons) or None


def _label(gcode: GcodeFile) -> str:
    return gcode.path.name


def check_compatible(a: GcodeFile, b: GcodeFile) -> None:
    """Raise CompatError unless the two files describe the same single-material plate."""
    for gcode in (a, b):
        tools = tools_used(gcode)
        if len(tools) > 1:
            raise CompatError(
                f"{_label(gcode)} uses {len(tools)} extruders "
                f"(tools {', '.join('T' + str(t) for t in sorted(tools))}). "
                f"{SINGLE_MATERIAL_MSG}"
            )
        if gcode.object_instances is not None and gcode.object_instances > 1:
            raise CompatError(
                f"{_label(gcode)} contains {gcode.object_instances} object instances. "
                f"{SINGLE_OBJECT_MSG}"
            )

    for key in COMPARED_FIELDS:
        left, right = a.config.get(key), b.config.get(key)
        if left is None and right is None:
            continue
        if left is None or right is None:
            present, missing = (a, b) if right is None else (b, a)
            raise CompatError(
                f"config mismatch on '{key}': {_label(present)} sets it, "
                f"{_label(missing)} does not. Re-slice both files from the same project."
            )
        if normalise(key, left) != normalise(key, right):
            raise CompatError(
                f"config mismatch on '{key}': "
                f"{_label(a)} = {left!r}, {_label(b)} = {right!r}. "
                "Both files must come from the same plate and printer profile."
            )

    count_a, count_b = a.object_instances, b.object_instances
    if count_a is not None and count_b is not None and count_a != count_b:
        raise CompatError(
            f"config mismatch on 'object instance count': "
            f"{_label(a)} has {count_a}, {_label(b)} has {count_b}."
        )

    polygons_a, polygons_b = object_polygons(a), object_polygons(b)
    if polygons_a and polygons_b and polygons_a != polygons_b:
        raise CompatError(
            f"config mismatch on 'object placement': the object outlines in "
            f"{_label(a)} and {_label(b)} differ. Do not move or rescale the object "
            "between the two slices."
        )

    footprint_a, footprint_b = first_layer_footprint(a), first_layer_footprint(b)
    if footprint_a is None or footprint_b is None:
        return
    if footprint_a.differs_from(footprint_b, _PLACEMENT_TOLERANCE_MM):
        raise CompatError(
            f"config mismatch on 'object placement': first layer covers {footprint_a} "
            f"in {_label(a)} but {footprint_b} in {_label(b)}. "
            "Do not move or rescale the object between the two slices."
        )


# ---------------------------------------------------------------
# weld.py
# ---------------------------------------------------------------

DEFAULT_STARTING_FLOW_RATIO = 0.8
DEFAULT_FINISHING_FLOW_RATIO = 0.25

_M73 = re.compile(r"^\s*M73\b", re.IGNORECASE)
_M73_P = re.compile(r"\bP(\d+)")
_M73_R = re.compile(r"\bR(\d+)")
_STATS_INFO = re.compile(r"^\s*SET_PRINT_STATS_INFO\b", re.IGNORECASE)
_TOTAL_LAYER = re.compile(r"(TOTAL_LAYER\s*=\s*)(\d+)", re.IGNORECASE)
_CURRENT_LAYER = re.compile(r"(CURRENT_LAYER\s*=\s*)(\d+)", re.IGNORECASE)
_TOTAL_LAYER_COMMENT = re.compile(
    r"^(\s*;\s*total layers? (?:count|number)\s*[:=]\s*)(\d+)", re.IGNORECASE
)
_TIME_COMMENT = re.compile(r"^\s*;\s*estimated .*printing time", re.IGNORECASE)
_FILAMENT_COMMENT = re.compile(
    r"^\s*;\s*(filament used \[(?:mm|cm3|g)\]|total filament used \[g\]"
    r"|total filament cost|total filament used for wipe tower \[g\])\s*=",
    re.IGNORECASE,
)
# BambuStudio writes its totals in a header block with colons instead of equals,
# and labels the volume cm^3 while computing it in mm^3. Both are reproduced as-is
# so the file stays consistent with what that slicer would have written.
_BAMBU_TOTAL = re.compile(
    r"^(\s*;\s*total filament (?:length \[mm\]|volume \[cm\^3\]|weight \[g\])\s*:\s*).*$",
    re.IGNORECASE,
)
_BAMBU_TIME = re.compile(r"^\s*;\s*model printing time\s*:", re.IGNORECASE)
_DURATION = re.compile(
    r"\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?\s*", re.IGNORECASE
)


class WeldError(Exception):
    """The requested weld cannot be performed."""


@dataclass(slots=True)
class Cut:
    """One weld point: where it was asked for and which layer it landed on."""

    requested: float
    z: float
    layer: int


@dataclass(slots=True)
class Slab:
    """A run of layers taken from one of the two files."""

    role: str  # "normal" or "vase"
    layers: tuple[int, int]  # first and last, in the source file's own numbering
    z: tuple[float, float]


@dataclass
class WeldResult:
    lines: list[str]
    newline: str
    cuts: list[Cut]
    slabs: list[Slab]
    e_mode_note: str
    ramps: list[str]
    stats_note: str
    stats_removed: list[str]
    warnings: list[str]

    # The single-cut shape, which is what almost every weld is.
    @property
    def cut_z(self) -> float:
        return self.cuts[0].z

    @property
    def requested_z(self) -> float:
        return self.cuts[0].requested

    @property
    def cut_layer(self) -> int:
        return self.cuts[0].layer

    @property
    def bottom_role(self) -> str:
        return self.slabs[0].role

    @property
    def top_role(self) -> str:
        return self.slabs[-1].role

    @property
    def bottom_range(self) -> tuple[int, int]:
        return self.slabs[0].layers

    @property
    def top_range(self) -> tuple[int, int]:
        return self.slabs[-1].layers

    @property
    def bottom_z(self) -> tuple[float, float]:
        return self.slabs[0].z

    @property
    def top_z(self) -> tuple[float, float]:
        return self.slabs[-1].z

    @property
    def ramp_note(self) -> str:
        return self.ramps[0]

    def summary(self) -> list[str]:
        out = [
            f"requested Z={cut.requested:.3f} is between layers, snapping down"
            for cut in self.cuts
            if abs(cut.requested - cut.z) > 1e-9
        ]
        label = "cut" if len(self.cuts) == 1 else "cuts"
        out.append(
            f"{label} snapped to "
            + ", ".join(f"Z={cut.z:.3f} (layer {cut.layer})" for cut in self.cuts)
        )
        out += [
            f"{slab.role}: layers {slab.layers[0]}-{slab.layers[1]} "
            f"(Z {slab.z[0]:.3f}-{slab.z[1]:.3f})"
            for slab in self.slabs
        ]
        out.append(f"E mode: {self.e_mode_note}")
        out += [f"transition ramp: {ramp}" for ramp in self.ramps]
        return out


def _ramp_factors(
    lines: list[str], cursor: Cursor, *, ramp_in: bool, flow: float
) -> dict[int, float]:
    """Per-line E scaling for a transition layer, mirroring OrcaSlicer's SpiralVase."""
    lengths = [
        (step.index, step.dist)
        for step in walk(lines, cursor.copy())
        if step.kind == "move" and step.delta is not None and step.delta > 0 and step.dist > 0
    ]
    total = sum(length for _, length in lengths)
    if total <= 0:
        return {}
    factors: dict[int, float] = {}
    travelled = 0.0
    for index, length in lengths:
        travelled += length
        fraction = travelled / total
        factors[index] = (
            flow + fraction * (1.0 - flow) if ramp_in else flow + (1.0 - fraction) * (1.0 - flow)
        )
    return factors


class _Sink:
    """Collects welded output, rewriting E into relative form as it goes."""

    def __init__(self) -> None:
        self.lines: list[str] = []
        self.net_e = 0.0
        self.saw_mode_command = False

    def append_generated(self, lines: list[str], cursor: Cursor | None = None) -> None:
        """Append lines vaseweld wrote itself, which are already relative E.

        Their E is counted towards the filament total, and any XY they carry is
        pushed into the cursor so later distances stay right.
        """
        for line in lines:
            self.lines.append(line)
            move = parse_move(line)
            if move is None:
                continue
            self.net_e += move.e or 0.0
            if cursor is not None:
                cursor.x = move.x if move.x is not None else cursor.x
                cursor.y = move.y if move.y is not None else cursor.y

    def feed(
        self, lines: list[str], cursor: Cursor, factors: dict[int, float] | None = None
    ) -> None:
        factors = factors or {}
        for step in walk(lines, cursor):
            if step.kind == "mode":
                self.saw_mode_command = True
                if parse_e_mode(step.line):
                    self.lines.append(step.line)
                else:
                    self.lines.append("M83 ; vaseweld: was M82, output is relative E")
                continue
            if step.kind == "move" and step.delta is not None:
                delta = step.delta
                factor = factors.get(step.index)
                if factor is not None and delta > 0:
                    delta = round(delta * factor, 5)
                self.net_e += delta
                self.lines.append(set_e(step.line, delta))
                continue
            self.lines.append(step.line)


def _config_floats(config: dict[str, str], key: str) -> list[float]:
    values = []
    for piece in config.get(key, "").split(","):
        try:
            values.append(float(piece.strip().rstrip("%")))
        except ValueError:
            continue
    return values


def _first_float(config: dict[str, str], *keys: str, default: float = 0.0) -> float:
    for key in keys:
        values = _config_floats(config, key)
        if values:
            return values[0]
    return default


def flow_ratio(config: dict[str, str], key: str, fallback: float) -> float:
    """Read a spiral flow ratio from the slicer config, falling back when absent."""
    values = _config_floats(config, key)
    return values[0] if values else fallback


@dataclass(slots=True)
class _Opening:
    """How a layer starts, which decides what the seam needs before it."""

    printing_at: int | None = None  # first move that both extrudes and moves in XY
    retracts: bool = False
    positions: bool = False  # reaches its start point with a travel move


def _opening(lines: list[str], cursor: Cursor) -> _Opening:
    opening = _Opening()
    for step in walk(lines, cursor.copy()):
        if step.kind != "move":
            continue
        move = parse_move(step.line)
        moves_xy = move is not None and (move.x is not None or move.y is not None)
        if step.delta is not None and step.delta > 0 and moves_xy:
            opening.printing_at = step.index
            return opening
        if step.delta is not None and step.delta < 0:
            opening.retracts = True
        elif moves_xy:
            opening.positions = True
    return opening


@dataclass(slots=True)
class _Seam:
    """Lines the weld inserts, and where each group has to go."""

    at_boundary: list[str]  # straight after the boundary, before the layer's own moves
    before_printing: list[str]  # just before the layer's first printing move


def _seam_lines(
    config: dict[str, str],
    seam: Cursor,
    resume: Cursor,
    opening: _Opening,
    *,
    retract: bool,
) -> _Seam:
    """Bridge the gap between where the file below stopped and what the file above assumes.

    ``seam`` is the state the file below leaves, ``resume`` the state the file above
    takes for granted. Slicers disagree about who owns the layer-change retraction:
    PrusaSlicer and OrcaSlicer put it at the start of the next layer, BambuStudio at
    the end of the previous one. Welding them naively leaves the nozzle either
    double-retracted or double-primed, so the difference has to be made up here.
    """
    length = _first_float(config, "retract_length", "retraction_length")
    speed = _first_float(config, "retract_speed", "retraction_speed", default=35.0) or 35.0
    recover = _first_float(config, "deretract_speed", "retract_speed", "retraction_speed") or speed

    def move_e(amount: float, label: str) -> str:
        rate = recover if amount > 0 else speed
        return f"G1 E{format_e(amount)} F{int(round(rate * 60))} ; vaseweld: seam {label}"

    travels = opening.printing_at is not None and not opening.positions
    if not travels or seam.x is None or seam.y is None:
        # The layer gets itself into position and primes itself, so only the leftover
        # retraction difference needs correcting, and it has to happen first.
        difference = seam.retracted - resume.retracted
        if abs(difference) < 1e-4:
            return _Seam([], [])
        return _Seam([move_e(difference, "prime" if difference > 0 else "retract")], [])

    lines = []
    top_up = max(0.0, length - seam.retracted) if retract else 0.0
    if top_up > 1e-4:
        lines.append(move_e(-top_up, "retract"))
    travel_speed = _first_float(config, "travel_speed", default=130.0) or 130.0
    lines.append(
        f"G1 X{seam.x:g} Y{seam.y:g} F{int(round(travel_speed * 60))}"
        " ; vaseweld: seam travel to where the next slice expects the nozzle"
    )
    prime = seam.retracted + top_up - resume.retracted
    if prime > 1e-4:
        lines.append(move_e(prime, "unretract"))
    return _Seam([], lines)


def _snap(top: GcodeFile, cut_z: float) -> Layer:
    lowest, highest = top.layers[1].z, top.layers[-1].z
    if cut_z < lowest - 1e-9 or cut_z > highest + 1e-9:
        raise WeldError(
            f"cut Z={cut_z:.3f} is outside the weldable range. "
            f"Valid range is Z {lowest:.3f} to {highest:.3f} "
            f"(layers 2 to {len(top.layers)} of {top.path.name})."
        )
    return [layer for layer in top.layers if layer.z <= cut_z + 1e-9][-1]


def _parse_duration(text: str) -> float | None:
    match = _DURATION.fullmatch(text)
    if not match or not any(match.groups()):
        return None
    days, hours, minutes, seconds = (int(group or 0) for group in match.groups())
    return days * 86400 + hours * 3600 + minutes * 60 + seconds


def _format_duration(seconds: float) -> str:
    total = int(round(seconds))
    days, total = divmod(total, 86400)
    hours, total = divmod(total, 3600)
    minutes, secs = divmod(total, 60)
    parts = []
    if days:
        parts.append(f"{days}d")
    if days or hours:
        parts.append(f"{hours}h")
    if days or hours or minutes:
        parts.append(f"{minutes}m")
    parts.append(f"{secs}s")
    return " ".join(parts)


def _time_comment_seconds(lines: list[str], needle: str) -> float | None:
    for line in lines:
        if needle in line.lower() and "=" in line:
            return _parse_duration(line.split("=", 1)[1])
    return None


def _m73_remaining(lines: list[str]) -> float | None:
    for line in lines:
        if _M73.match(line):
            match = _M73_R.search(line)
            if match:
                return float(match.group(1))
    return None


@dataclass
class _Progress:
    """Remaps M73 reporting across every seam using the files' own R values.

    R is minutes remaining, so a region that starts with R=a and ends with R=b took
    a-b minutes. Summing those gives the welded total, and any line inside a region
    is that region's own elapsed time plus everything before it.
    """

    spans: list[tuple[float, float]]  # (R at the start, R at the end) per region
    fractions: list[float]  # each region's share of its own file's time

    @property
    def durations(self) -> list[float]:
        return [max(0.0, start - end) for start, end in self.spans]

    @property
    def welded_total(self) -> float:
        return sum(self.durations)

    def rewrite(self, line: str, region: int) -> str:
        found = _M73_R.search(line)
        if found is None:
            return line
        total = self.welded_total
        before = sum(self.durations[:region])
        elapsed = before + max(0.0, self.spans[region][0] - float(found.group(1)))
        elapsed = min(elapsed, total)
        percent = 0 if total <= 0 else min(100, int(round(100 * elapsed / total)))
        line = _M73_R.sub(f"R{int(round(total - elapsed))}", line, count=1)
        return _M73_P.sub(f"P{percent}", line, count=1)


def _build_progress(regions: list["_Region"]) -> _Progress | None:
    spans: list[tuple[float, float]] = []
    fractions: list[float] = []
    for position, region in enumerate(regions):
        source = region.source
        file_total = _m73_remaining(source.lines)
        # The header belongs to the first region, so it starts at the file's total.
        start = (
            file_total if position == 0 else _m73_remaining(source.lines[region.layers[0].start :])
        )
        end = _m73_remaining(source.lines[region.layers[-1].end :])
        if file_total is None or start is None or end is None or file_total <= 0:
            return None
        spans.append((start, end))
        fractions.append(max(0.0, start - end) / file_total)
    return _Progress(spans, fractions)


def _material_totals(net_e_mm: float, config: dict[str, str]) -> dict[str, float]:
    diameter = _first_float(config, "filament_diameter", default=1.75) or 1.75
    volume_cm3 = net_e_mm * math.pi * (diameter / 2.0) ** 2 / 1000.0
    grams = volume_cm3 * _first_float(config, "filament_density")
    return {
        "filament used [mm]": net_e_mm,
        "filament used [cm3]": volume_cm3,
        "total filament used [g]": grams,
        "total filament cost": grams / 1000.0 * _first_float(config, "filament_cost"),
    }


def _renumber_layers(
    body: list[str], footer: list[str], spans: list[tuple[int, int]], total_layers: int
) -> None:
    """Fix Klipper's SET_PRINT_STATS_INFO counters and the total-layer comments.

    A marker is numbered by the output layer it sits in, so a file whose first
    layer carries no marker keeps its off-by-one relationship intact.
    """
    starts = [start for start, _ in spans]
    for offset, chunk in ((0, body), (len(body), footer)):
        for i, line in enumerate(chunk):
            if _STATS_INFO.match(line):
                line = _TOTAL_LAYER.sub(lambda m: f"{m.group(1)}{total_layers}", line)
                if _CURRENT_LAYER.search(line):
                    position = bisect.bisect_right(starts, i + offset)
                    number = spans[position - 1][1] if position else 1
                    line = _CURRENT_LAYER.sub(lambda m: f"{m.group(1)}{number}", line)
                chunk[i] = line
            elif _TOTAL_LAYER_COMMENT.match(line):
                chunk[i] = _TOTAL_LAYER_COMMENT.sub(lambda m: f"{m.group(1)}{total_layers}", line)


def _welded_seconds(regions: list["_Region"], progress: _Progress | None) -> float | None:
    """Take each region's share of its own file's time estimate and add them up.

    The shares come from the M73 remaining times, which are whole minutes, so the
    file's own second-resolution estimate is what gets scaled.
    """
    if progress is None:
        return None
    total = 0.0
    for region, fraction in zip(regions, progress.fractions):
        seconds = _time_comment_seconds(region.source.lines, "estimated printing time")
        if seconds is None:
            return progress.welded_total * 60.0
        total += seconds * fraction
    return total


def _bambu_total(line: str, material: dict[str, float]) -> str:
    label = line.split(":", 1)[0]
    if "length" in label.lower():
        return f"{label}: {material['filament used [mm]']:.2f}"
    if "volume" in label.lower():
        return f"{label}: {material['filament used [cm3]'] * 1000:.2f}"
    return f"{label}: {material['total filament used [g]']:.2f}"


def _rewrite_stats(
    lines: list[str],
    *,
    seconds: float | None,
    first_layer_seconds: float | None,
    material: dict[str, float],
) -> None:
    out: list[str] = []
    for line in lines:
        if _BAMBU_TOTAL.match(line):
            out.append(_bambu_total(line, material))
            continue
        if _BAMBU_TIME.match(line):
            if seconds is not None:
                out.append(
                    f"; model printing time: {_format_duration(seconds)}; "
                    f"total estimated time: {_format_duration(seconds)}"
                )
            continue
        if _FILAMENT_COMMENT.match(line):
            key = line.split("=", 1)[0].strip(" ;").lower()
            if key in material:
                out.append(f"; {key} = {material[key]:.2f}")
            else:
                out.append(line)
            continue
        if _TIME_COMMENT.match(line):
            value = first_layer_seconds if "first layer" in line.lower() else seconds
            if value is not None:
                label = line.split("=", 1)[0].rstrip()
                out.append(f"{label} = {_format_duration(value)}")
            continue
        if re.match(r"^\s*;\s*use_relative_e_distances\s*=", line):
            out.append("; use_relative_e_distances = 1")
            continue
        out.append(line)
    lines[:] = out


def _provenance(plan: _Plan) -> list[str]:
    where = ", ".join(f"Z={cut.z:.3f} (layer {cut.layer})" for cut in plan.cuts)
    banner = [f"; vaseweld {__version__}: welded at {where}"]
    banner += [
        f";   layers {region.layers[0].index}-{region.layers[-1].index} from "
        f"{region.source.path.name} ({region.role})"
        for region in plan.regions
    ]
    banner.append(";   extrusion is relative (M83) across the whole file")
    return banner


def _e_mode_note(bottom: GcodeFile, top: GcodeFile) -> str:
    if bottom.relative_e and top.relative_e:
        return "relative (unchanged)"
    if not bottom.relative_e and not top.relative_e:
        return "absolute -> relative (converted)"
    return (
        f"mixed ({bottom.path.name}={'relative' if bottom.relative_e else 'absolute'}, "
        f"{top.path.name}={'relative' if top.relative_e else 'absolute'}) "
        "-> relative (converted)"
    )


@dataclass
class _Region:
    """A run of layers taken from one file, between two cuts."""

    source: GcodeFile
    role: str
    layers: list[Layer]
    ramp_in: bool = False  # the spiral starts here
    ramp_out: bool = False  # the spiral ends here


@dataclass
class _Plan:
    """Which layers come from which file, and how the flow ramps are configured."""

    regions: list[_Region]
    cuts: list[Cut]
    start_flow: float
    finish_flow: float
    warnings: list[str] = field(default_factory=list)

    @property
    def total_layers(self) -> int:
        return sum(len(region.layers) for region in self.regions)


@dataclass
class _Spliced:
    """The emitted file, still in two halves so the footer can be rewritten alone."""

    body: list[str]
    footer: list[str]
    spans: list[tuple[int, int]]  # (index in body, output layer number)
    region_starts: list[int]  # index in body where each region begins
    net_e: float


def _plan(
    sources: dict[str, GcodeFile],
    cut_zs: list[float],
    *,
    first_role: str,
    start_flow: float | None,
    finish_flow: float | None,
) -> _Plan:
    """Alternate between the two files at every cut, lowest first."""
    roles = [first_role]
    for _ in cut_zs:
        roles.append("vase" if roles[-1] == "normal" else "normal")

    cuts: list[Cut] = []
    for requested, role in zip(sorted(cut_zs), roles[1:]):
        layer = _snap(sources[role], requested)
        cuts.append(Cut(requested=requested, z=layer.z, layer=layer.index))
    for earlier, later in zip(cuts, cuts[1:]):
        if later.z <= earlier.z + 1e-9:
            raise WeldError(
                f"cuts at Z={earlier.z:.3f} and Z={later.z:.3f} land on the same layer; "
                "every weld needs at least one layer of its own."
            )

    regions: list[_Region] = []
    warnings: list[str] = []
    for position, role in enumerate(roles):
        source = sources[role]
        low = cuts[position - 1].z if position else None
        high = cuts[position].z if position < len(cuts) else None
        layers = [
            layer
            for layer in source.layers
            if (low is None or layer.z >= low - 1e-9) and (high is None or layer.z < high - 1e-9)
        ]
        if not layers:
            span = f"Z {low if low is not None else 0:.3f} to {high:.3f}" if high else "the top"
            raise WeldError(
                f"{source.path.name} has no layer for {span}; that leaves an empty section."
            )
        regions.append(
            _Region(
                source=source,
                role=role,
                layers=layers,
                ramp_in=role == "vase" and position > 0,
                ramp_out=role == "vase" and position < len(roles) - 1,
            )
        )
        if position:
            warnings += _seam_step_warning(source, layers[0], regions[position - 1].layers[-1])
        if len(layers) == 1 and regions[-1].ramp_in and regions[-1].ramp_out:
            regions[-1].ramp_out = False
            warnings.append(
                f"the vase section at Z={layers[0].z:.3f} is a single layer, so it ramps "
                "flow up but not back down; move the cuts further apart"
            )

    vase = next((region.source for region in regions if region.role == "vase"), None)
    vase_config = vase.config if vase else {}
    return _Plan(
        regions=regions,
        cuts=cuts,
        start_flow=start_flow
        if start_flow is not None
        else flow_ratio(vase_config, "spiral_starting_flow_ratio", DEFAULT_STARTING_FLOW_RATIO),
        finish_flow=finish_flow
        if finish_flow is not None
        else flow_ratio(vase_config, "spiral_finishing_flow_ratio", DEFAULT_FINISHING_FLOW_RATIO),
        warnings=warnings,
    )


def _seam_step_warning(top: GcodeFile, cut_layer: Layer, bottom_last: Layer) -> list[str]:
    """The layer above the cut was sliced expecting a particular layer below it.

    Only reachable through --force, because compat.py refuses a layer_height mismatch,
    but a forced weld can otherwise squeeze a thick layer into a thin gap in silence.
    """
    step = cut_layer.z - bottom_last.z
    expected = _first_float(top.config, "layer_height")
    if expected <= 0 or abs(step - expected) <= 0.02:
        return []
    return [
        f"the seam leaves a {step:.3f} mm step but {top.path.name} slices "
        f"{expected:.3f} mm layers, so layer {cut_layer.index} will lay "
        f"{expected / step:.0%} of the material that gap can take"
    ]


def _splice(plan: _Plan, *, seam_retract: bool) -> _Spliced:
    first = plan.regions[0]
    sink = _Sink()
    spans: list[tuple[int, int]] = []
    region_starts: list[int] = []
    cursor = Cursor(relative_e=first.source.relative_e)
    sink.feed(first.source.lines[: first.source.header_end], cursor)
    if not sink.saw_mode_command:
        sink.lines += ["M83 ; vaseweld: output uses relative E", "G92 E0"]

    for position, region in enumerate(plan.regions):
        opening = None
        bridge = None
        if position:
            previous = plan.regions[position - 1]
            sink.lines.append(
                f"; vaseweld: weld boundary at Z={region.layers[0].z:.3f}, "
                f"{previous.role} below / {region.role} above"
            )
            sink.lines.append("G92 E0")
            seam = cursor.copy()
            cursor = state_at(region.source, region.layers[0].start)
            resume = cursor.copy()
            # The travel goes to this file's own last position; the nozzle is still
            # wherever the file below left it until then.
            seam.x, seam.y = cursor.x, cursor.y
            # A vase layer expects the nozzle to already be on its spiral, because in
            # the source file the previous layer ended there. After a weld it is
            # wherever the other file stopped, so the seam has to travel it back.
            opening = _opening(region.source.layer_lines(region.layers[0]), cursor)
            bridge = _seam_lines(region.source.config, seam, resume, opening, retract=seam_retract)
            sink.append_generated(bridge.at_boundary, cursor)

        region_starts.append(len(sink.lines))
        last = len(region.layers) - 1
        for offset, layer in enumerate(region.layers):
            lines = region.source.layer_lines(layer)
            spans.append((len(sink.lines), len(spans) + 1))
            if offset == 0 and bridge and bridge.before_printing:
                sink.feed(lines[: opening.printing_at], cursor)
                sink.append_generated(bridge.before_printing, cursor)
                lines = lines[opening.printing_at :]
            factors = None
            if region.ramp_in and offset == 0:
                factors = _ramp_factors(lines, cursor, ramp_in=True, flow=plan.start_flow)
            elif region.ramp_out and offset == last:
                factors = _ramp_factors(lines, cursor, ramp_in=False, flow=plan.finish_flow)
            sink.feed(lines, cursor, factors)

    tail = plan.regions[-1].source
    footer_sink = _Sink()
    footer_sink.feed(tail.lines[tail.footer_start :], cursor)
    return _Spliced(
        body=sink.lines,
        footer=footer_sink.lines,
        spans=spans,
        region_starts=region_starts,
        net_e=sink.net_e + footer_sink.net_e,
    )


def _finalise(plan: _Plan, spliced: _Spliced) -> tuple[str, list[str]]:
    """Fix the counters, progress and totals that a splice invalidates.

    Returns a human-readable note and the list of things that had to be removed
    because they could not be recomputed.
    """
    body, footer = spliced.body, spliced.footer
    first, last = plan.regions[0].source, plan.regions[-1].source
    removed: list[str] = []
    progress = _build_progress(plan.regions)
    _renumber_layers(body, footer, spliced.spans, plan.total_layers)

    if progress is None:
        before = len(body) + len(footer)
        body[:] = [line for line in body if not _M73.match(line)]
        footer[:] = [line for line in footer if not _M73.match(line)]
        note = "M73 progress stripped"
        if before > len(body) + len(footer):
            removed.append("M73 progress reporting")
    else:
        starts = spliced.region_starts
        for i, line in enumerate(body):
            if _M73.match(line):
                body[i] = progress.rewrite(line, max(0, bisect.bisect_right(starts, i) - 1))
        for i, line in enumerate(footer):
            if _M73.match(line):
                footer[i] = progress.rewrite(line, len(starts) - 1)
        note = "M73 progress remapped"

    seconds = _welded_seconds(plan.regions, progress)
    stats = {
        "seconds": seconds,
        "first_layer_seconds": _time_comment_seconds(
            first.lines, "estimated first layer printing time"
        ),
        "material": _material_totals(spliced.net_e, last.config),
    }
    _rewrite_stats(body, **stats)
    _rewrite_stats(footer, **stats)
    if seconds is None:
        if _time_comment_seconds(last.lines, "estimated printing time") is not None:
            removed.append("the printing time estimate")
        return note + ", time estimate stripped", removed
    return f"{note}, time estimate {_format_duration(seconds)}", removed


def _ramp_notes(plan: _Plan) -> list[str]:
    notes = []
    for region in plan.regions:
        if region.ramp_in:
            notes.append(f"{plan.start_flow:.2f} -> 1.00 over layer {region.layers[0].index}")
        if region.ramp_out:
            notes.append(f"1.00 -> {plan.finish_flow:.2f} over layer {region.layers[-1].index}")
    return notes


def weld(
    normal: GcodeFile,
    vase: GcodeFile,
    cut_z: float | list[float],
    *,
    first_role: str = "normal",
    start_flow: float | None = None,
    finish_flow: float | None = None,
    seam_retract: bool = True,
) -> WeldResult:
    """Alternate between the two slices at every cut height, lowest layer first.

    One cut gives ``first_role`` below and the other file above. More cuts keep
    alternating, so two cuts make a solid base, a vase body and a solid lid.
    """
    sources = {"normal": normal, "vase": vase}
    cut_zs = [cut_z] if isinstance(cut_z, (int, float)) else list(cut_z)
    if not cut_zs:
        raise WeldError("no cut height given")

    plan = _plan(
        sources,
        cut_zs,
        first_role=first_role,
        start_flow=start_flow,
        finish_flow=finish_flow,
    )
    spliced = _splice(plan, seam_retract=seam_retract)
    stats_note, stats_removed = _finalise(plan, spliced)

    body = spliced.body
    return WeldResult(
        lines=body[:1] + _provenance(plan) + body[1:] + spliced.footer,
        newline=plan.regions[0].source.newline,
        cuts=plan.cuts,
        slabs=[
            Slab(
                role=region.role,
                layers=(region.layers[0].index, region.layers[-1].index),
                z=(region.layers[0].z, region.layers[-1].z),
            )
            for region in plan.regions
        ],
        e_mode_note=_e_mode_note(normal, vase),
        ramps=_ramp_notes(plan),
        stats_note=stats_note,
        stats_removed=stats_removed,
        warnings=plan.warnings,
    )


# ---------------------------------------------------------------
# validate.py
# ---------------------------------------------------------------

_WAIT_TEMP = re.compile(r"^\s*M(109|190)\b", re.IGNORECASE)
_TEMP_S = re.compile(r"\b[SR](\d+(?:\.\d+)?)")

# An extrusion of 25x the file's own median mm-of-filament-per-mm-of-travel is
# not a thick line, it is an absolute E value that leaked into a relative file.
_E_RATIO_LIMIT = 25.0
_MIN_RATIO_SAMPLES = 20
_MIN_TRAVEL_MM = 0.05
_MAX_RETRACT_MM = 20.0
# A healthy file never has more than one retraction's worth of filament pulled
# back at a time. Twice that means an unretract went missing.
_RETRACT_PEAK_LIMIT = 1.5
_RETRACT_TROUGH_LIMIT = -0.5


@dataclass
class Problem:
    line: int
    check: str
    message: str

    def __str__(self) -> str:
        return f"  line {self.line}: {self.message}"


@dataclass
class Report:
    path: Path
    relative_e: bool
    temperature_timelines: int = 1
    retract_length: float = 0.0
    peak_retracted: float = 0.0
    problems: list[Problem] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.problems

    def summary(self) -> str:
        mode = "relative" if self.relative_e else "absolute"
        plural = "" if self.temperature_timelines == 1 else "s"
        if self.ok:
            return (
                f"OK: Z monotonic, E coherent ({mode}), retractions balanced, "
                f"{self.temperature_timelines} temperature timeline{plural}"
            )
        count = len(self.problems)
        return f"FAIL: {count} problem{'' if count == 1 else 's'} in {self.path.name}"


def _body(gcode: GcodeFile) -> list[str]:
    return gcode.lines[gcode.header_end : gcode.footer_start]


def _check_z(gcode: GcodeFile, report: Report) -> None:
    """Extruding moves may never drop below a height already printed."""
    highest = None
    for offset, line in enumerate(_body(gcode)):
        move = parse_move(line)
        if move is None or move.z is None or not move.e:
            continue  # travel and z-hop may legitimately go down
        if highest is not None and move.z < highest - 1e-6:
            report.problems.append(
                Problem(
                    gcode.header_end + offset + 1,
                    "z",
                    f"Z goes backwards while extruding ({highest:.3f} -> {move.z:.3f})",
                )
            )
            return
        highest = move.z if highest is None else max(highest, move.z)


def _check_extrusion(gcode: GcodeFile, report: Report) -> None:
    """Decode the body's extrusion and record mode switches, blowouts and retractions."""
    cursor = gcode.cursor()
    ratios: list[tuple[int, float, float]] = []
    for step in walk(_body(gcode), cursor):
        number = gcode.header_end + step.index + 1
        if step.kind == "mode":
            if cursor.relative_e != gcode.relative_e:
                report.problems.append(
                    Problem(
                        number,
                        "e",
                        f"extruder mode switches to "
                        f"{'relative' if cursor.relative_e else 'absolute'} "
                        "in the middle of the print",
                    )
                )
            continue
        if step.delta is None:
            continue
        if step.dist > _MIN_TRAVEL_MM:
            if step.delta > 0:
                ratios.append((number, step.delta / step.dist, step.delta))
            continue
        if step.dist:
            continue  # a sub-0.05 mm move is neither a printing line nor a retraction
        if abs(step.delta) > _MAX_RETRACT_MM:
            report.problems.append(
                Problem(
                    number,
                    "e",
                    f"E jumps by {step.delta:.3f} mm with no XY movement; that is not a retraction",
                )
            )
    _check_extrusion_rate(ratios, report)


def _check_extrusion_rate(ratios: list[tuple[int, float, float]], report: Report) -> None:
    if len(ratios) < _MIN_RATIO_SAMPLES:
        return
    median = statistics.median(ratio for _, ratio, _ in ratios)
    limit = median * _E_RATIO_LIMIT
    for number, ratio, delta in ratios:
        if ratio > limit:
            report.problems.append(
                Problem(
                    number,
                    "e",
                    f"extrudes {delta:.5f} mm over {delta / ratio:.3f} mm of travel "
                    f"({ratio:.3f} mm/mm against a file median of {median:.3f}); "
                    "an absolute E value in a relative file looks like this",
                )
            )
            return


def _retract_length(gcode: GcodeFile, largest: float) -> float:
    """The file's configured retraction, or the biggest one it actually performs."""
    for key in ("retract_length", "retraction_length"):
        for piece in gcode.config.get(key, "").split(","):
            try:
                value = float(piece.strip())
            except ValueError:
                continue
            if value > 0:
                return value
    return largest


def _check_retractions(gcode: GcodeFile, report: Report) -> None:
    """Retraction is a running state, not a line count.

    Slicers disagree about how a retraction is spelled: PrusaSlicer uses one
    E-only move, BambuStudio splits it between a wiping move and an E-only tail.
    Tracking how much filament is pulled back at any moment works for both.
    """
    cursor = gcode.cursor()
    peak = trough = 0.0
    peak_at = trough_at = gcode.header_end
    largest = 0.0
    for step in walk(_body(gcode), cursor):
        if step.kind != "move" or not step.delta:
            continue
        if step.delta < 0:
            largest = max(largest, -step.delta)
        elif step.dist:
            continue
        if cursor.retracted > peak:
            peak, peak_at = cursor.retracted, gcode.header_end + step.index + 1
        if cursor.retracted < trough:
            trough, trough_at = cursor.retracted, gcode.header_end + step.index + 1

    length = _retract_length(gcode, largest)
    report.retract_length = length
    report.peak_retracted = peak
    if length <= 0:
        return
    if peak > length * _RETRACT_PEAK_LIMIT:
        report.problems.append(
            Problem(
                peak_at,
                "retract",
                f"retractions do not balance: {peak:.3f} mm pulled back at once against a "
                f"retraction length of {length:.3f} mm, so an unretract is missing",
            )
        )
    if trough < length * _RETRACT_TROUGH_LIMIT:
        report.problems.append(
            Problem(
                trough_at,
                "retract",
                f"retractions do not balance: {-trough:.3f} mm primed past the retracted "
                f"state, so there is an unretract with no retract",
            )
        )


def _check_temperature(gcode: GcodeFile, report: Report) -> None:
    """A blocking heat-and-wait between the first and last extrusion is a second start-up."""
    body = _body(gcode)
    printing = [
        offset
        for offset, line in enumerate(body)
        if (move := parse_move(line)) and move.e and (move.x is not None or move.y is not None)
    ]
    if not printing:
        return
    for offset in range(printing[0], printing[-1] + 1):
        code, _ = strip_comment(body[offset])
        if not _WAIT_TEMP.match(code):
            continue
        value = _TEMP_S.search(code)
        if value is None or float(value.group(1)) <= 0:
            continue
        report.temperature_timelines += 1
        report.problems.append(
            Problem(
                gcode.header_end + offset + 1,
                "temperature",
                f"blocking temperature wait ({code.strip()}) in the middle of the print; "
                "this is the start-up sequence of a second file",
            )
        )


def check(path: str | Path) -> Report:
    """Run every check over one file. Raises GcodeError if it cannot be parsed."""
    gcode = parse_file(path)
    report = Report(path=gcode.path, relative_e=gcode.relative_e)
    _check_z(gcode, report)
    _check_extrusion(gcode, report)
    _check_retractions(gcode, report)
    _check_temperature(gcode, report)
    report.problems.sort(key=lambda problem: problem.line)
    return report


# ---------------------------------------------------------------
# preview.py
# ---------------------------------------------------------------

_BANNER_CUTS = re.compile(r"layer (\d+)\)")
_BANNER_SLAB = re.compile(r";\s+layers (\d+)-(\d+) from (\S+) \((\w+)\)")

# Colour by source, matching the images in the README.
NORMAL = "#4682be"
VASE = "#e1783c"
_WIDTH_STEP = 0.05  # mm; a path is broken when its bead changes bucket


@dataclass
class Section:
    """One run of layers, as named by the ``; vaseweld`` banner in the file."""

    role: str
    source: str
    first: int
    last: int


@dataclass
class Preview:
    name: str
    layers: list[dict] = field(default_factory=list)
    sections: list[Section] = field(default_factory=list)
    cuts: list[int] = field(default_factory=list)
    bounds: tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0)


def read_banner(gcode: GcodeFile) -> tuple[list[Section], list[int]]:
    """Recover the weld layout from the ``; vaseweld`` block, if the file has one."""
    sections: list[Section] = []
    cuts: list[int] = []
    for line in gcode.lines[: gcode.header_end]:
        if line.startswith("; vaseweld ") and "welded at" in line:
            cuts = [int(n) for n in _BANNER_CUTS.findall(line)]
        match = _BANNER_SLAB.match(line)
        if match:
            sections.append(
                Section(
                    role=match.group(4),
                    source=match.group(3),
                    first=int(match.group(1)),
                    last=int(match.group(2)),
                )
            )
    if sum(s.last - s.first + 1 for s in sections) != len(gcode.layers):
        return [], []
    return sections, cuts


def layer_paths(
    lines: list[str], cursor: Cursor, layer_height: float, filament: float
) -> list[dict]:
    """Extruding moves of one layer, joined into polylines of near-constant width.

    Takes the running cursor rather than a layer index: layers are contiguous, so
    walking the file once is O(n) where re-deriving the state per layer is O(n^2).
    """
    area_of_filament = math.pi * (filament / 2.0) ** 2
    paths: list[dict] = []
    points: list[float] = []
    bucket = None
    previous = (cursor.x, cursor.y)

    def flush() -> None:
        nonlocal points, bucket
        if len(points) >= 4 and bucket is not None:
            paths.append({"w": round(bucket, 3), "p": points})
        points = []
        bucket = None

    for step in walk(lines, cursor):
        if step.kind != "move":
            continue
        here = (cursor.x, cursor.y)
        printing = step.delta and step.delta > 0 and step.dist > 0 and None not in previous
        if not printing:
            flush()
            previous = here
            continue
        width = bead_width(step.delta * area_of_filament / step.dist, layer_height)
        rounded = round(width / _WIDTH_STEP) * _WIDTH_STEP
        if bucket is None:
            bucket = rounded
            points = [round(previous[0], 2), round(previous[1], 2)]
        elif abs(rounded - bucket) > 1e-9 or (points[-2], points[-1]) != (
            round(previous[0], 2),
            round(previous[1], 2),
        ):
            flush()
            bucket = rounded
            points = [round(previous[0], 2), round(previous[1], 2)]
        points += [round(here[0], 2), round(here[1], 2)]
        previous = here
    flush()
    return paths


def build(gcode: GcodeFile) -> Preview:
    layer_height = config_float(gcode.config, "layer_height", 0.2)
    filament = config_float(gcode.config, "filament_diameter", 1.75)
    sections, cuts = read_banner(gcode)
    preview = Preview(name=gcode.path.name, sections=sections, cuts=cuts)

    xs: list[float] = []
    ys: list[float] = []
    cursor = gcode.cursor()
    for _ in walk(gcode.lines[: gcode.layers[0].start], cursor):
        pass  # the start gcode leaves the nozzle somewhere; layer 1 continues from it
    for layer in gcode.layers:
        paths = layer_paths(gcode.layer_lines(layer), cursor, layer_height, filament)
        preview.layers.append({"z": round(layer.z, 3), "paths": paths})
        for path in paths:
            xs += path["p"][0::2]
            ys += path["p"][1::2]
    if xs:
        preview.bounds = (min(xs), min(ys), max(xs), max(ys))
    return preview


def render(preview: Preview) -> str:
    """The whole page: data, drawing code and controls in one file."""
    roles = ["normal"] * len(preview.layers)
    for section in preview.sections:
        for index in range(section.first - 1, min(section.last, len(roles))):
            roles[index] = section.role
    data = {
        "name": preview.name,
        "bounds": [round(v, 2) for v in preview.bounds],
        "cuts": preview.cuts,
        "roles": roles,
        "sections": [
            {"role": s.role, "source": s.source, "first": s.first, "last": s.last}
            for s in preview.sections
        ],
        "layers": preview.layers,
    }
    legend = "".join(
        f'<span class="key"><i style="background:{VASE if s.role == "vase" else NORMAL}"></i>'
        f"layers {s.first}-{s.last} from {s.source} ({s.role})</span>"
        for s in preview.sections
    )
    return (
        _TEMPLATE.replace("__TITLE__", preview.name)
        .replace("__LEGEND__", legend)
        .replace("__DATA__", json.dumps(data, separators=(",", ":")))
        .replace("__NORMAL__", NORMAL)
        .replace("__VASE__", VASE)
    )


def write(path: Path, gcode_path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(build(parse_file(gcode_path))), encoding="utf-8")
    return path


_TEMPLATE = """<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>__TITLE__ - vaseweld preview</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body { margin: 0; font: 14px/1.5 system-ui, sans-serif; background: #fafaf9; color: #3c3c41;
         overflow-x: hidden; }
  header { padding: 14px 18px 8px; }
  h1 { margin: 0; font-size: 16px; font-weight: 600; }
  .sub { color: #85858c; font-size: 13px; }
  .legend { margin: 8px 0 0; display: flex; flex-wrap: wrap; gap: 14px; font-size: 13px; }
  .key { display: flex; align-items: center; gap: 6px; }
  .key i { width: 11px; height: 11px; border-radius: 2px; display: inline-block; }
  main { display: flex; gap: 18px; padding: 0 18px 18px; flex-wrap: wrap; }
  /* The canvas must be sized by CSS. With only the width/height attributes, setting
     canvas.width for the device pixel ratio also changes its layout width, which
     feeds back and blows the element up on any HiDPI screen. */
  canvas { background: #fff; border: 1px solid #e6e6e3; border-radius: 6px; touch-action: none;
           display: block; width: 100%; height: auto; }
  #top { aspect-ratio: 1 / 1; }
  #side { aspect-ratio: 3 / 4; }
  .panel { display: flex; flex-direction: column; gap: 6px; min-width: 0; flex: 1 1 300px;
           max-width: 560px; }
  .cap { font-size: 12px; color: #85858c; }
  .controls { padding: 0 18px 20px; display: flex; align-items: center; gap: 12px;
              flex-wrap: wrap; }
  @media (max-width: 700px) {
    header, main, .controls { padding-left: 12px; padding-right: 12px; }
    .legend { gap: 6px; flex-direction: column; }
    .readout { min-width: 0; font-size: 13px; }
    /* Both views, their labels and the slider have to fit one phone screen, or the
       front view draws its content below the fold where nobody sees it. */
    h1 { font-size: 15px; }
    .sub { display: none; }
    .legend { font-size: 12px; margin-top: 6px; }
    .cap { font-size: 11px; }
    canvas { max-height: 29vh; }
    main { gap: 8px; padding-bottom: 8px; }
    .panel { gap: 2px; }
    .controls { position: sticky; bottom: 0; padding-top: 10px; padding-bottom: 12px;
                background: #fafaf9; border-top: 1px solid #e6e6e3; }
  }
  @media (max-width: 700px) and (prefers-color-scheme: dark) {
    .controls { background: #17171a; border-top-color: #34343a; }
  }
  input[type=range] { flex: 1 1 180px; min-width: 0; }
  button { font: inherit; padding: 4px 12px; border: 1px solid #d0d0cc; border-radius: 5px;
           background: #fff; cursor: pointer; }
  button:hover { background: #f2f2ef; }
  .readout { font-variant-numeric: tabular-nums; min-width: 190px; }
  label { display: flex; align-items: center; gap: 6px; }
  @media (prefers-color-scheme: dark) {
    body { background: #17171a; color: #dcdce0; }
    canvas { background: #1f1f23; border-color: #34343a; }
    button { background: #232329; color: inherit; border-color: #3a3a42; }
    button:hover { background: #2b2b32; }
  }
</style>
<header>
  <h1>__TITLE__</h1>
  <div class="sub">Every bead drawn at the width the G-code actually asks for.
    Drag the slider past a weld to watch stacked layers become a spiral.</div>
  <div class="legend">__LEGEND__</div>
</header>
<main>
  <div class="panel"><canvas id="top" width="520" height="520"></canvas>
    <div class="cap">from above</div></div>
  <div class="panel"><canvas id="side" width="380" height="520"></canvas>
    <div class="cap">from the front</div></div>
</main>
<div class="controls">
  <button id="play">Play</button>
  <input type="range" id="slider" min="1" value="1">
  <span class="readout" id="readout"></span>
  <label><input type="checkbox" id="stack"> stack the top view</label>
</div>
<script>
// Wrapped: a bare `const top` at global scope collides with the non-configurable
// window.top and silently stops the whole script from running.
(function () {
const DATA = __DATA__;
const COLOUR = { normal: "__NORMAL__", vase: "__VASE__" };
const layers = DATA.layers, roles = DATA.roles, cuts = new Set(DATA.cuts);
const [minX, minY, maxX, maxY] = DATA.bounds;
const minZ = layers[0].z, maxZ = layers[layers.length - 1].z;
const topView = document.getElementById("top"), sideView = document.getElementById("side");
const slider = document.getElementById("slider"), readout = document.getElementById("readout");
const stack = document.getElementById("stack"), play = document.getElementById("play");
slider.max = layers.length;
// Land on the first weld, which is the thing worth looking at, not the finished lid.
slider.value = cuts.size ? Math.min(...DATA.cuts) : layers.length;

function fit(canvas, w, h) {
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  const box = canvas.getBoundingClientRect();
  canvas.width = Math.max(1, Math.round(box.width * dpr));
  canvas.height = Math.max(1, Math.round(box.height * dpr));
  const ctx = canvas.getContext("2d");
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  const pad = 14;
  const scale = Math.min((box.width - 2 * pad) / w, (box.height - 2 * pad) / h);
  return { ctx, scale, pad, width: box.width, height: box.height };
}

function strokePath(ctx, pts, project) {
  ctx.beginPath();
  for (let i = 0; i < pts.length; i += 2) {
    const [x, y] = project(pts[i], pts[i + 1]);
    i ? ctx.lineTo(x, y) : ctx.moveTo(x, y);
  }
  ctx.stroke();
}

function draw() {
  const upto = +slider.value;
  const z = layers[upto - 1].z;
  readout.textContent = `layer ${upto} of ${layers.length}   Z ${z.toFixed(2)} mm` +
    (cuts.has(upto) ? "   \\u2190 weld" : "");

  const w = maxX - minX, h = maxY - minY;
  const a = fit(topView, w, h);
  a.ctx.clearRect(0, 0, a.width, a.height);
  const ox = (a.width - w * a.scale) / 2, oy = (a.height - h * a.scale) / 2;
  const toTop = (x, y) => [ox + (x - minX) * a.scale, a.height - oy - (y - minY) * a.scale];

  const zSpan = Math.max(maxZ - minZ, 0.001);
  const b = fit(sideView, w, zSpan);
  b.ctx.clearRect(0, 0, b.width, b.height);
  const sx = (b.width - w * b.scale) / 2, sy = (b.height - zSpan * b.scale) / 2;
  const toSide = (x, zz) => [sx + (x - minX) * b.scale, b.height - sy - (zz - minZ) * b.scale];

  a.ctx.lineCap = b.ctx.lineCap = "round";
  a.ctx.lineJoin = b.ctx.lineJoin = "round";
  // The front view builds up so you can see the sections stack. The top view shows
  // the layer under the slider, because 200 stacked loops is just a filled disc.
  const topFrom = stack.checked ? 1 : Math.max(1, upto - 1);
  for (let i = 1; i <= upto; i++) {
    const layer = layers[i - 1];
    const colour = COLOUR[roles[i - 1]] || COLOUR.normal;
    b.ctx.globalAlpha = i === upto ? 1 : 0.35 + 0.65 * (i / upto);
    b.ctx.strokeStyle = colour;
    for (const path of layer.paths) {
      b.ctx.lineWidth = Math.max(path.w * b.scale, 0.6);
      b.ctx.beginPath();
      for (let k = 0; k < path.p.length; k += 2) {
        const [px, py] = toSide(path.p[k], layer.z);
        k ? b.ctx.lineTo(px, py) : b.ctx.moveTo(px, py);
      }
      b.ctx.stroke();
    }
    if (i < topFrom) continue;
    a.ctx.globalAlpha = i === upto ? 1 : 0.22;
    a.ctx.strokeStyle = colour;
    for (const path of layer.paths) {
      a.ctx.lineWidth = Math.max(path.w * a.scale, 0.6);
      strokePath(a.ctx, path.p, toTop);
    }
  }
  a.ctx.globalAlpha = b.ctx.globalAlpha = 1;
}

let timer = null;
play.onclick = () => {
  if (timer) { clearInterval(timer); timer = null; play.textContent = "Play"; return; }
  play.textContent = "Pause";
  if (+slider.value >= layers.length) slider.value = 1;
  timer = setInterval(() => {
    slider.value = +slider.value + 1;
    draw();
    if (+slider.value >= layers.length) { clearInterval(timer); timer = null; play.textContent = "Play"; }
  }, 1000 / 60);
};
let queued = false;
function schedule() {
  if (queued) return;
  queued = true;
  requestAnimationFrame(() => { queued = false; draw(); });
}
slider.oninput = schedule;
stack.onchange = schedule;
addEventListener("resize", schedule);
draw();
})();
</script>
</html>
"""


# ---------------------------------------------------------------
# cli.py
# ---------------------------------------------------------------

write_preview = write
run_check = check


EXIT_OK = 0
EXIT_PROBLEMS = 1
EXIT_USAGE = 2

_EPILOG = r"""Slice the same plate twice, once with Spiral Vase off and once on, then:

  vaseweld layers body.gcode
  vaseweld weld --normal base.gcode --vase body.gcode --at 12.4 -o out.gcode
  vaseweld check out.gcode
  vaseweld preview out.gcode

Repeat --at to alternate again, so a solid base, a vase body and a solid lid is:

  vaseweld weld --normal base.gcode --vase body.gcode --at 12.4 --at 30 -o out.gcode

The output always uses relative extrusion (M83). Absolute-E inputs are converted.

As a slicer post-processing script, leave out the side the slicer is producing and
let it append the temporary file path:

  vaseweld weld --normal C:\prints\base.gcode --at 12.4
"""


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="vaseweld",
        description="Weld two G-code files sliced from the same plate at a chosen Z height.",
        epilog=_EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--version", action="version", version=f"vaseweld {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    weld_cmd = sub.add_parser(
        "weld",
        help="splice a normal slice and a vase slice at a Z height",
        description="Splice a normal slice and a spiral vase slice at a Z height.",
    )
    weld_cmd.add_argument("--normal", type=Path, help="the non-vase slice")
    weld_cmd.add_argument("--vase", type=Path, help="the spiral vase slice")
    weld_cmd.add_argument(
        "--at",
        required=True,
        type=float,
        metavar="Z",
        action="append",
        help="cut height in mm; repeat it to alternate again, so two cuts give a "
        "solid base, a vase body and a solid lid",
    )
    weld_cmd.add_argument("-o", "--output", type=Path, help="file to write")
    weld_cmd.add_argument(
        "gcode",
        nargs="?",
        type=Path,
        help="the file a slicer post-processing hook just produced; it takes whichever "
        "of --normal or --vase you left out, and is rewritten in place unless -o is given",
    )
    weld_cmd.add_argument(
        "--vase-first",
        action="store_true",
        help="start with the vase part below the first cut instead of the normal part",
    )
    weld_cmd.add_argument(
        "--start-flow",
        type=float,
        metavar="RATIO",
        help="flow ratio the vase transition layer ramps up from "
        "(default: spiral_starting_flow_ratio from the vase file, else 0.8)",
    )
    weld_cmd.add_argument(
        "--finish-flow",
        type=float,
        metavar="RATIO",
        help="flow ratio the last vase layer ramps down to "
        "(default: spiral_finishing_flow_ratio from the vase file, else 0.25)",
    )
    weld_cmd.add_argument(
        "--no-seam-retract",
        action="store_true",
        help="do not retract before the seam travel; the retraction state is still matched",
    )
    weld_cmd.add_argument(
        "--dry-run",
        action="store_true",
        help="report the plan and write nothing",
    )
    weld_cmd.add_argument(
        "--force",
        action="store_true",
        help="weld even if the two files disagree on printer or plate settings",
    )

    preview_cmd = sub.add_parser(
        "preview",
        help="write a self-contained HTML page you can open and scrub through",
        description="Draw the toolpath into one HTML file: no server, no dependencies.",
    )
    preview_cmd.add_argument("file", type=Path, help="G-code file to draw")
    preview_cmd.add_argument("-o", "--output", type=Path, help="defaults to FILE.html")

    layers_cmd = sub.add_parser(
        "layers",
        help="list the layer heights a file can be cut at",
        description="Report the Z ladder, so you can pick a cut without guessing.",
    )
    layers_cmd.add_argument("file", type=Path, help="G-code file to inspect")
    layers_cmd.add_argument(
        "--all", action="store_true", help="print every layer, not just the summary"
    )

    check_cmd = sub.add_parser(
        "check",
        help="verify a G-code file is coherent enough to print",
        description="Verify Z, extrusion, retractions and the temperature timeline.",
    )
    check_cmd.add_argument("file", type=Path, help="G-code file to check")
    return parser


def _validate_flow(name: str, value: float | None) -> None:
    if value is not None and not 0.0 <= value <= 1.0:
        raise WeldError(f"{name} must be between 0 and 1, got {value}")


def _resolve_inputs(args: argparse.Namespace) -> tuple[Path, Path, Path]:
    """Work out the two inputs and the destination, honouring a trailing hook file."""
    normal, vase, output = args.normal, args.vase, args.output
    if args.gcode is not None:
        if normal is not None and vase is not None:
            raise WeldError(
                f"--normal and --vase are both set, so {args.gcode} has no role. "
                "Drop one of them when a slicer passes the file it just wrote."
            )
        if normal is None:
            normal = args.gcode
        else:
            vase = args.gcode
        output = output or args.gcode
    if normal is None or vase is None:
        raise WeldError(
            "need both slices: pass --normal and --vase, or pass one of them plus the "
            "file a slicer post-processing hook hands over as the last argument"
        )
    if output is None:
        raise WeldError("no destination: pass -o/--output")
    if output.suffix.lower() == ".bgcode":
        raise WeldError(
            f"{output}: vaseweld reads binary G-code but cannot write it. "
            "Give -o a .gcode name, or turn off 'Supports binary G-code' in "
            "Print Settings > Output options on the profile that runs this hook. "
            "Printers that take .bgcode take plain G-code too."
        )
    return normal, vase, output


def _run_weld(args: argparse.Namespace, out: "object") -> int:
    _validate_flow("--start-flow", args.start_flow)
    _validate_flow("--finish-flow", args.finish_flow)
    normal_path, vase_path, output = _resolve_inputs(args)

    normal = parse_file(normal_path)
    vase = parse_file(vase_path)
    try:
        check_compatible(normal, vase)
    except CompatError as exc:
        if not args.force:
            raise
        print(f"warning: {exc}", file=sys.stderr)
        print("warning: continuing because --force was given", file=sys.stderr)

    result = weld(
        normal,
        vase,
        args.at,
        first_role="vase" if args.vase_first else "normal",
        start_flow=args.start_flow,
        finish_flow=args.finish_flow,
        seam_retract=not args.no_seam_retract,
    )

    if not args.dry_run:
        text = result.newline.join(result.lines) + result.newline
        try:
            output.write_text(text, encoding="utf-8", newline="")
        except OSError as exc:
            raise GcodeError(f"{output}: cannot write ({exc.strerror or exc})") from exc

    for line in result.summary():
        print(line, file=out)
    verb = "would write" if args.dry_run else "wrote"
    print(f"{verb} {output} ({len(result.lines)} lines)", file=out)
    for warning in result.warnings:
        print(f"warning: {warning}", file=sys.stderr)
    if result.stats_removed:
        print(
            "note: removed "
            + " and ".join(result.stats_removed)
            + ", which cannot be recomputed from these two files",
            file=sys.stderr,
        )
    destination = os.environ.get("SLIC3R_PP_OUTPUT_NAME")
    if destination:
        print(f"slicer will save it as {destination}", file=out)
    return EXIT_OK


def _run_preview(args: argparse.Namespace, out: "object") -> int:
    destination = args.output or args.file.with_suffix(".html")
    try:
        written = write_preview(destination, args.file)
    except OSError as exc:
        raise GcodeError(f"{destination}: cannot write ({exc.strerror or exc})") from exc
    size = written.stat().st_size / 1024
    print(f"wrote {written} ({size:.0f} KB), open it in any browser", file=out)
    return EXIT_OK


def _run_layers(args: argparse.Namespace, out: "object") -> int:
    gcode = parse_file(args.file)
    zs = [layer.z for layer in gcode.layers]
    steps = {round(b - a, 4) for a, b in zip(zs, zs[1:])}
    print(f"{gcode.path.name}: {len(zs)} layers, Z {zs[0]:.3f} to {zs[-1]:.3f}", file=out)
    if len(steps) == 1:
        print(f"layer height: {next(iter(steps)):.3f} mm", file=out)
    else:
        print(
            f"layer height: varies, {min(steps):.3f} to {max(steps):.3f} mm. "
            "Slice both files at a fixed layer height before welding.",
            file=out,
        )
    print(
        f"weldable range: Z {zs[1]:.3f} to {zs[-1]:.3f} (layers 2 to {len(zs)})",
        file=out,
    )
    if args.all:
        for layer in gcode.layers:
            print(f"  layer {layer.index:4d}  Z {layer.z:.3f}", file=out)
    return EXIT_OK


def _run_check(args: argparse.Namespace, out: "object") -> int:
    report = run_check(args.file)
    print(report.summary(), file=out)
    for problem in report.problems:
        print(problem, file=out)
    return EXIT_OK if report.ok else EXIT_PROBLEMS


def main(argv: list[str] | None = None, out: "object" = None) -> int:
    out = out or sys.stdout
    args = _build_parser().parse_args(argv)
    try:
        if args.command == "weld":
            return _run_weld(args, out)
        if args.command == "layers":
            return _run_layers(args, out)
        if args.command == "preview":
            return _run_preview(args, out)
        return _run_check(args, out)
    except (GcodeError, CompatError, WeldError) as exc:
        print(f"vaseweld: {exc}", file=sys.stderr)
        return EXIT_USAGE
    except KeyboardInterrupt:
        print("vaseweld: interrupted", file=sys.stderr)
        return EXIT_USAGE

if __name__ == "__main__":
    sys.exit(main())
