from __future__ import annotations

import shutil
import subprocess
import zipfile
from pathlib import Path

import pytest

import vaseweld.slicer
from vaseweld.parser import parse_file
from vaseweld.preflight import MODEL_CONFIG
from vaseweld.slicer import PRINT_CONFIG

ROOT = Path(__file__).parent.parent
FIXTURES = Path(__file__).parent / "fixtures"
EXAMPLES = ROOT / "examples"


def fixture(name: str) -> Path:
    path = FIXTURES / name
    assert path.exists(), f"missing fixture {name}"
    return path


def example(name: str) -> Path:
    path = EXAMPLES / name
    assert path.exists(), f"missing example {name}"
    return path


def multi_material_3mf(tmp_path: Path, extruders: tuple[int, int] = (1, 2)) -> Path:
    """cylinder_6mm.3mf with its one volume split across two extruders.

    Derived rather than committed: a real multi-material project carries a second
    mesh, and the only part preflight reads is the per-volume extruder key.
    """
    source, destination = fixture("cylinder_6mm.3mf"), tmp_path / "two_materials.3mf"
    config = zipfile.ZipFile(source).read(MODEL_CONFIG).decode("utf-8")
    start = config.index("  <volume")
    end = config.index("  </volume>") + len("  </volume>\n")
    volume = config[start:end]
    halves = "".join(
        volume.replace('firstid="0" lastid="191"', f'firstid="{first}" lastid="{last}"').replace(
            "  </volume>",
            f'   <metadata type="volume" key="extruder" value="{extruder}"/>\n  </volume>',
        )
        for extruder, (first, last) in zip(extruders, ((0, 95), (96, 191)))
    )
    shutil.copyfile(source, destination)
    _replace_member(destination, MODEL_CONFIG, config[:start] + halves + config[end:])
    return destination


def project_3mf(tmp_path: Path, name: str, **settings: str) -> Path:
    """cylinder_6mm.3mf carrying a print config, the way a project saved from the GUI does.

    Headless PrusaSlicer never writes this member, so it cannot be produced by the
    binary. The "; key = value" shape is the one 2.9.6 reads back.
    """
    destination = tmp_path / name
    shutil.copyfile(fixture("cylinder_6mm.3mf"), destination)
    lines = ["; generated by PrusaSlicer 2.9.6+win64"]
    lines += [f"; {key} = {value}" for key, value in settings.items()]
    _replace_member(destination, PRINT_CONFIG, "\n".join(lines) + "\n")
    return destination


def _replace_member(archive_path: Path, name: str, text: str) -> None:
    """Rewrite one member of a zip, adding it if the archive did not have it."""
    with zipfile.ZipFile(archive_path) as archive:
        items = [(item, archive.read(item.filename)) for item in archive.infolist()]
    with zipfile.ZipFile(archive_path, "w", zipfile.ZIP_DEFLATED) as out:
        for item, data in items:
            out.writestr(item, text.encode("utf-8") if item.filename == name else data)
        if not any(item.filename == name for item, _ in items):
            out.writestr(name, text.encode("utf-8"))


class FakePrusaSlicer:
    """Stands in for the binary: answers --help with a banner, writes a fixture per pass.

    Real PrusaSlicer is only present behind VASEWELD_E2E, so everything else drives
    this instead. It records every argv it is handed, which is what the tests assert on.
    """

    BANNER = "PrusaSlicer-2.9.6 based on Slic3r (with GUI support)"

    def __init__(self, path: Path) -> None:
        self.path = path
        self.banner = self.BANNER
        self.normal = "prusaslicer_normal_6mm.gcode"
        self.vase = "prusaslicer_vase_6mm.gcode"
        self.returncode = 0
        self.stderr = ""
        self.calls: list[list[str]] = []

    def __call__(self, argv, **kwargs):
        argv = [str(part) for part in argv]
        self.calls.append(argv)
        if "--help" in argv:
            return subprocess.CompletedProcess(
                argv, 0, f"{self.banner}\nhttps://github.com/prusa3d/PrusaSlicer\n", ""
            )
        produce = self.vase if "--spiral-vase=1" in argv else self.normal
        if produce is not None:
            shutil.copyfile(fixture(produce), argv[argv.index("--output") + 1])
        return subprocess.CompletedProcess(argv, self.returncode, "", self.stderr)

    @property
    def slices(self) -> list[list[str]]:
        return [argv for argv in self.calls if "--help" not in argv]


@pytest.fixture
def fake_slicer(monkeypatch, tmp_path):
    fake = FakePrusaSlicer(tmp_path / "bin" / "prusa-slicer-console.exe")
    fake.path.parent.mkdir(parents=True, exist_ok=True)
    fake.path.write_text("stand-in for prusa-slicer\n", encoding="utf-8")
    monkeypatch.setattr(vaseweld.slicer.subprocess, "run", fake)
    return fake


@pytest.fixture(scope="session")
def ps_normal():
    return parse_file(fixture("prusaslicer_normal_40mm.gcode"))


@pytest.fixture(scope="session")
def ps_vase():
    return parse_file(fixture("prusaslicer_vase_40mm.gcode"))


@pytest.fixture(scope="session")
def orca_normal():
    return parse_file(fixture("orcaslicer_normal_40mm.gcode"))


@pytest.fixture(scope="session")
def orca_vase():
    return parse_file(fixture("orcaslicer_vase_40mm.gcode"))


@pytest.fixture(scope="session")
def klipper_normal():
    return parse_file(fixture("klipper_normal_6mm.gcode"))


@pytest.fixture(scope="session")
def klipper_vase():
    return parse_file(fixture("klipper_vase_6mm.gcode"))


@pytest.fixture(scope="session")
def small_normal():
    return parse_file(fixture("prusaslicer_normal_6mm.gcode"))


@pytest.fixture(scope="session")
def small_vase():
    return parse_file(fixture("prusaslicer_vase_6mm.gcode"))


def weld_argv(
    normal="prusaslicer_normal_6mm.gcode",
    vase="prusaslicer_vase_6mm.gcode",
    at="3",
    output=None,
    extra=(),
    trailing=None,
):
    """Build a `weld` argv. A None name omits that flag; a Path is used verbatim."""
    argv = ["weld"]
    for flag, value in (("--normal", normal), ("--vase", vase)):
        if value is not None:
            argv += [flag, str(value if isinstance(value, Path) else fixture(value))]
    argv += ["--at", at, *extra]
    if output is not None:
        argv += ["-o", str(output)]
    if trailing is not None:
        argv.append(str(trailing))
    return argv


@pytest.fixture(scope="session")
def bambu_normal():
    return parse_file(fixture("bambustudio_normal_40mm.gcode"))


@pytest.fixture(scope="session")
def bambu_vase():
    return parse_file(fixture("bambustudio_vase_40mm.gcode"))
