"""Concatenate the package into the standalone ``vaseweld.py`` at the repo root.

The standalone file is generated, never edited by hand. ``tests/test_single_file.py``
fails if it drifts from the package.
"""

from __future__ import annotations

import argparse
import ast
import re
from pathlib import Path

MODULES = ("__init__", "parser", "compat", "weld", "validate", "cli")

HEADER = '''\
#!/usr/bin/env python3
"""vaseweld {version} - weld two G-code files so spiral vase mode can start or stop partway up.

Standalone build: no install, no dependencies, Python 3.10+.
Generated by tools/build_single_file.py; edit src/vaseweld/ instead.

    python vaseweld.py weld --normal base.gcode --vase body.gcode --at 12.4 -o out.gcode
    python vaseweld.py check out.gcode

MIT licensed. https://github.com/Booyaka101/vaseweld
"""

from __future__ import annotations

{imports}
'''

FOOTER = """

if __name__ == "__main__":
    sys.exit(main())
"""


def _is_relative_import(node: ast.stmt) -> bool:
    return isinstance(node, ast.ImportFrom) and node.level > 0


def _strip_docstring(source: str) -> str:
    tree = ast.parse(source)
    if not tree.body or not isinstance(tree.body[0], ast.Expr):
        return source
    first = tree.body[0]
    if not isinstance(first.value, ast.Constant) or not isinstance(first.value.value, str):
        return source
    lines = source.splitlines()
    return "\n".join(lines[first.end_lineno :])


def _top_level_names(tree: ast.Module) -> set[str]:
    names = set()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(node.name)
        elif isinstance(node, ast.Assign):
            names.update(t.id for t in node.targets if isinstance(t, ast.Name))
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names.add(node.target.id)
    return names


def build(src: Path) -> str:
    plain: set[str] = {"import sys"}
    from_imports: dict[str, set[str]] = {}
    sections: list[str] = []
    defined: dict[str, str] = {}
    version = ""

    for name in MODULES:
        source = _strip_docstring((src / f"{name}.py").read_text(encoding="utf-8"))
        tree = ast.parse(source)
        for clash in _top_level_names(tree) & defined.keys():
            raise SystemExit(
                f"{name}.py redefines {clash!r}, already defined in {defined[clash]}.py; "
                "the single-file build would silently drop one of them"
            )
        defined.update({key: name for key in _top_level_names(tree)})

        drop: set[int] = set()
        aliases: list[str] = []
        for node in tree.body:
            if isinstance(node, ast.If) and ast.unparse(node.test) == "__name__ == '__main__'":
                drop.update(range(node.lineno, node.end_lineno + 1))
                continue
            if isinstance(node, ast.Import):
                plain.update(f"import {a.name}" for a in node.names)
            elif isinstance(node, ast.ImportFrom):
                if _is_relative_import(node):
                    aliases += [f"{a.asname} = {a.name}" for a in node.names if a.asname]
                elif node.module != "__future__":
                    from_imports.setdefault(node.module, set()).update(a.name for a in node.names)
            else:
                continue
            drop.update(range(node.lineno, node.end_lineno + 1))

        lines = source.splitlines()
        body = [line for i, line in enumerate(lines, 1) if i not in drop]
        match = re.search(r'^__version__ = "(.+)"$', source, re.MULTILINE)
        if match:
            version = match.group(1)
        text = "\n".join(body).strip("\n")
        if aliases:
            text = "\n".join(aliases) + "\n\n\n" + text
        if text:
            sections.append(
                "# ---------------------------------------------------------------\n"
                f"# {name}.py\n"
                "# ---------------------------------------------------------------\n\n"
                f"{text}"
            )

    ordered = sorted(plain) + [
        f"from {module} import {', '.join(sorted(names))}"
        for module, names in sorted(from_imports.items())
    ]
    header = HEADER.format(version=version, imports="\n".join(ordered))
    return header + "\n\n" + "\n\n\n".join(sections) + FOOTER


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", type=Path, default=root / "vaseweld.py")
    ap.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = ap.parse_args()

    text = build(root / "src" / "vaseweld")
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current != text:
            raise SystemExit(f"{args.out} is stale; run python tools/build_single_file.py")
        print(f"{args.out} is up to date")
        return
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
